"""Service registry - single source of truth for what runs on the VPS.

Reflects the FULL VPS state after comprehensive audit (2026-05-19).
Total: 60+ services across 8 groups.
"""

from __future__ import annotations

GROUPS: dict[str, dict] = {
    "multica": {
        "label": "Multica Dashboard",
        "icon": "📊",
        "color": "#3b82f6",
        "services": [
            {
                "name": "Multica Frontend",
                "port": 3002,
                "kind": "docker",
                "url": "https://multica.83-171-249-32.nip.io/",
                "container": "multica-frontend-1",
                "desc": "React UI for Multica",
            },
            {
                "name": "Multica Backend",
                "port": 8080,
                "kind": "docker",
                "url": "https://multica.83-171-249-32.nip.io/api/",
                "container": "multica-backend-1",
                "desc": "Core API",
            },
            {
                "name": "Multica Postgres",
                "port": 5435,
                "kind": "docker",
                "url": None,
                "container": "multica-postgres-1",
                "desc": "PostgreSQL (multica/multica123)",
            },
            {
                "name": "C360 API",
                "port": 9062,
                "kind": "systemd",
                "url": "https://multica.83-171-249-32.nip.io/api/c360/health",
                "unit": "multica-c360.service",
                "desc": "Customer 360 (1,218 unified customers)",
            },
            {
                "name": "Inventory API",
                "port": 9063,
                "kind": "systemd",
                "url": "https://multica.83-171-249-32.nip.io/api/inv/",
                "unit": "multica-inv.service",
                "desc": "Inventory analytics",
            },
            {
                "name": "Master Dashboard API",
                "port": 9103,
                "kind": "systemd",
                "url": None,
                "unit": "multica-master-api.service",
                "desc": "Master dashboard backend",
            },
            {
                "name": "Dashboard API",
                "port": 9095,
                "kind": "systemd",
                "url": None,
                "unit": "multica-dashboard-api.service",
                "desc": "Multica dashboard API",
            },
            {
                "name": "Activity Feed API",
                "port": 9102,
                "kind": "systemd",
                "url": None,
                "unit": "multica-activity-feed.service",
                "desc": "Event stream",
            },
            {
                "name": "Federated Search API",
                "port": 9092,
                "kind": "systemd",
                "url": None,
                "unit": "multica-federated-search.service",
                "desc": "Cross-source search",
            },
            {
                "name": "RAG Search API",
                "port": 9096,
                "kind": "systemd",
                "url": None,
                "unit": "multica-rag.service",
                "desc": "RAG retrieval",
            },
            {
                "name": "Metrics API",
                "port": 9101,
                "kind": "systemd",
                "url": None,
                "unit": "multica-metrics-api.service",
                "desc": "Metrics endpoint",
            },
            {
                "name": "Monitor API",
                "port": 9058,
                "kind": "systemd",
                "url": None,
                "unit": "multica-monitor.service",
                "desc": "Health monitor",
            },
            {
                "name": "Smart Workload Router",
                "port": 9101,
                "kind": "systemd",
                "url": None,
                "unit": "multica-smart-router-webhook.service",
                "desc": "AI workload routing",
            },
            {
                "name": "Agent Runtime Daemon",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "multica-daemon.service",
                "desc": "Agent runtime",
            },
            {
                "name": "GitHub Webhook",
                "port": 9090,
                "kind": "systemd",
                "url": None,
                "unit": "multica-github-webhook.service",
                "desc": "GitHub event bridge",
            },
            {
                "name": "Webhook Refresh Trigger",
                "port": 9099,
                "kind": "systemd",
                "url": None,
                "unit": "multica-webhook-refresh-trigger.service",
                "desc": "Refresh trigger",
            },
            {
                "name": "Usage Tail",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "multica-usage-tail.service",
                "desc": "anthropic-shim usage logger",
            },
        ],
    },
    "paperclip": {
        "label": "Paperclip Business",
        "icon": "📎",
        "color": "#8b5cf6",
        "services": [
            {
                "name": "Paperclip AI (native)",
                "port": 3100,
                "kind": "systemd",
                "url": None,
                "unit": "paperclip.service",
                "desc": "Multi-company agent orchestration",
            },
            {
                "name": "Paperclip Biz Server",
                "port": 3200,
                "kind": "docker",
                "url": "http://83.171.249.32:3200/",
                "container": "paperclip-biz-server-1",
                "desc": "Paperclip Business UI + API",
            },
            {
                "name": "Paperclip Biz DB",
                "port": 5433,
                "kind": "docker",
                "url": None,
                "container": "paperclip-biz-db-1",
                "desc": "PostgreSQL 17 for Paperclip",
            },
            {
                "name": "Strip Proxy",
                "port": 4000,
                "kind": "systemd",
                "url": None,
                "unit": "strip-proxy.service",
                "desc": "Paperclip ↔ 9Router bridge",
            },
            {
                "name": "Newtech PG (clone)",
                "port": 5436,
                "kind": "docker",
                "url": None,
                "container": "newtech_pg",
                "desc": "PostgreSQL 16 clone",
            },
            {
                "name": "Newtech Redis",
                "port": 6381,
                "kind": "docker",
                "url": None,
                "container": "newtech_redis",
                "desc": "Redis 7 for Paperclip stack",
            },
        ],
    },
    "hermes": {
        "label": "Hermes Agent",
        "icon": "🚀",
        "color": "#ec4899",
        "services": [
            {
                "name": "Hermes Agent (8061)",
                "port": 8061,
                "kind": "systemd",
                "url": None,
                "unit": "hermes-gateway.service",
                "desc": "Hermes Agent v0.14.0 messaging gateway",
            },
            {
                "name": "Hermes Workspace (web)",
                "port": 8051,
                "kind": "docker",
                "url": "https://workspace.83-171-249-32.nip.io/",
                "container": "hermes-workspace-jadeed",
                "desc": "Native workspace UI",
            },
            {
                "name": "Hermes WebUI",
                "port": 3000,
                "kind": "systemd",
                "url": "https://hermes.83-171-249-32.nip.io/",
                "unit": "hermes-webui.service",
                "desc": "Browser interface",
            },
            {
                "name": "Hermes Workspace svc",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "hermes-workspace.service",
                "desc": "Workspace systemd unit",
            },
            {
                "name": "Hermes Native Dashboard",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "hermes-dashboard-native.service",
                "desc": "Native dashboard",
            },
            {
                "name": "Hermes CDP Bridge",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "hermes-cdp-bridge.service",
                "desc": "Chrome DevTools proxy",
            },
        ],
    },
    "openclaw": {
        "label": "OpenClaw",
        "icon": "🦞",
        "color": "#dc2626",
        "services": [
            {
                "name": "OpenClaw Gateway",
                "port": 3080,
                "kind": "systemd",
                "url": None,
                "unit": "openclaw-gateway.service",
                "desc": "OpenClaw HTTP gateway (Claude CLI bridge)",
            },
            {
                "name": "OpenClaw Watchdog",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "openclaw-watchdog.service",
                "desc": "Keeps OpenClaw gateway alive",
            },
            {
                "name": "OpenClaw Auth",
                "port": 3082,
                "kind": "process",
                "url": None,
                "process": "openclaw",
                "desc": "OpenClaw auth endpoint (401 = healthy)",
            },
            {
                "name": "OpenClaw Tools",
                "port": 8787,
                "kind": "process",
                "url": None,
                "process": "openclaw",
                "desc": "OpenClaw tools port",
            },
        ],
    },
    "router": {
        "label": "LLM Router Stack",
        "icon": "🧠",
        "color": "#10b981",
        "services": [
            {
                "name": "9Router",
                "port": 20128,
                "kind": "systemd",
                "url": "https://9router.83-171-249-32.nip.io/login",
                "unit": "9router.service",
                "desc": "Smart LLM routing v0.4.55",
            },
            {
                "name": "Anthropic Shim",
                "port": 8060,
                "kind": "systemd",
                "url": None,
                "unit": "anthropic-shim.service",
                "desc": "Claude Max CLI shim",
            },
            {
                "name": "OpenAI Shim",
                "port": 8070,
                "kind": "systemd",
                "url": None,
                "unit": "openai-shim.service",
                "desc": "OpenRouter proxy (OpenAI-compatible)",
            },
            {
                "name": "Ollama",
                "port": 11434,
                "kind": "systemd",
                "url": None,
                "unit": "ollama.service",
                "desc": "Local Ollama (nomic-embed)",
            },
        ],
    },
    "mcp": {
        "label": "MCP Servers",
        "icon": "🔌",
        "color": "#f59e0b",
        "services": [
            {
                "name": "GitHub MCP",
                "port": 8064,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-github.service",
                "desc": "gh CLI wrapper (SSE)",
            },
            {
                "name": "Hermes MCP",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-hermes.service",
                "desc": "Hermes Agent MCP HTTP",
            },
            {
                "name": "Integrations MCP",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-integrations.service",
                "desc": "Hermes+OpenClaw+Shopify+Zoho+Search",
            },
            {
                "name": "Postgres MCP",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-postgres.service",
                "desc": "Read-only PG access",
            },
            {
                "name": "Search Tools MCP",
                "port": 8065,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-search-tools.service",
                "desc": "Gemini+DuckDuckGo+Jina+Brave+Firecrawl",
            },
            {
                "name": "Shopify MCP",
                "port": 8063,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-shopify.service",
                "desc": "Read-only Shopify (Newtechkw)",
            },
            {
                "name": "Workspace MCP",
                "port": 8066,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-workspace.service",
                "desc": "FS + git access (read-only)",
            },
            {
                "name": "Workspace Stream MCP",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-workspace-stream.service",
                "desc": "Streamable HTTP variant",
            },
            {
                "name": "Zoho MCP",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "mcp-zoho.service",
                "desc": "Read-only Zoho (Newtechkw)",
            },
            {
                "name": "gbrain HTTP MCP",
                "port": 3132,
                "kind": "systemd",
                "url": "https://gbrain.83-171-249-32.nip.io/",
                "unit": "gbrain.service",
                "desc": "Knowledge graph MCP",
            },
        ],
    },
    "suna": {
        "label": "Suna Tunnels",
        "icon": "☀️",
        "color": "#fbbf24",
        "services": [
            {
                "name": "Suna API Tunnel",
                "port": 8050,
                "kind": "systemd",
                "url": None,
                "unit": "suna-tunnel-api.service",
                "desc": "Cloudflared tunnel for Suna API",
            },
            {
                "name": "Suna Supabase Tunnel",
                "port": 54321,
                "kind": "systemd",
                "url": None,
                "unit": "suna-tunnel-supabase.service",
                "desc": "Cloudflared tunnel for Supabase",
            },
            {
                "name": "Suna Web Tunnel",
                "port": 3050,
                "kind": "systemd",
                "url": None,
                "unit": "suna-tunnel-web.service",
                "desc": "Cloudflared tunnel for Suna Web",
            },
        ],
    },
    "infra": {
        "label": "Infrastructure",
        "icon": "⚙️",
        "color": "#6b7280",
        "services": [
            {
                "name": "nginx",
                "port": 443,
                "kind": "systemd",
                "url": "https://multica.83-171-249-32.nip.io/",
                "unit": "nginx.service",
                "desc": "Reverse proxy + Let's Encrypt",
            },
            {
                "name": "Docker",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "docker.service",
                "desc": "Container runtime",
            },
            {
                "name": "Native Postgres",
                "port": 5432,
                "kind": "systemd",
                "url": None,
                "unit": "postgresql@16-main.service",
                "desc": "Native PostgreSQL 16",
            },
            {
                "name": "Redis (md)",
                "port": 6379,
                "kind": "docker",
                "url": None,
                "container": "md-redis",
                "desc": "Multica Redis",
            },
            {
                "name": "Fail2Ban",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "fail2ban.service",
                "desc": "SSH brute-force protection (96 banned)",
            },
            {
                "name": "Tailscale",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "tailscaled.service",
                "desc": "Tailscale VPN mesh",
            },
            {
                "name": "Containerd",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "containerd.service",
                "desc": "Container runtime daemon",
            },
            {
                "name": "Cron",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "cron.service",
                "desc": "Scheduled jobs",
            },
            {
                "name": "rsyslog",
                "port": None,
                "kind": "systemd",
                "url": None,
                "unit": "rsyslog.service",
                "desc": "System logging service",
            },
            {
                "name": "Dream Dashboard",
                "port": 9200,
                "kind": "systemd",
                "url": "https://dashboard.83-171-249-32.nip.io/",
                "unit": "dream-dashboard.service",
                "desc": "This dashboard 🎯",
            },
        ],
    },
}

# Login info - separate to allow easier redaction / role-based reveal.
LOGINS = {
    "Multica Frontend": {
        "url": "https://multica.83-171-249-32.nip.io/",
        "user": "admin",
        "notes": "Multica admin (see vault for password)",
    },
    "Multica Postgres": {
        "host": "127.0.0.1:5435",
        "user": "multica",
        "db": "multica",
        "pass": "multica123",
    },
    "Paperclip Biz Server": {
        "url": "http://83.171.249.32:3200/",
        "user": "first-run signup",
    },
    "Paperclip Biz DB": {"host": "0.0.0.0:5433", "user": "see Paperclip env"},
    "Newtech PG (clone)": {"host": "127.0.0.1:5436", "user": "see container env"},
    "Hermes Workspace (web)": {
        "url": "https://workspace.83-171-249-32.nip.io/",
        "user": "Hermes built-in auth",
    },
    "Hermes WebUI": {
        "url": "https://hermes.83-171-249-32.nip.io/",
        "user": "Hermes built-in auth",
    },
    "9Router": {
        "url": "https://9router.83-171-249-32.nip.io/login",
        "user": "API key in /root/.9router/db/data.sqlite",
    },
    "OpenClaw Gateway": {
        "url": "http://127.0.0.1:3080/",
        "user": "JWT in /root/.9router/jwt-secret",
    },
    "gbrain HTTP MCP": {
        "url": "https://gbrain.83-171-249-32.nip.io/",
        "user": "MCP token auth",
    },
    "Dream Dashboard": {
        "url": "https://dashboard.83-171-249-32.nip.io/auth/login",
        "user": "PIN in /opt/dream-dashboard/dashboard.env",
    },
}


def all_services() -> list[dict]:
    out = []
    for gid, g in GROUPS.items():
        for s in g["services"]:
            out.append(
                {
                    **s,
                    "group": gid,
                    "group_label": g["label"],
                    "group_color": g["color"],
                    "group_icon": g["icon"],
                }
            )
    return out
